### ISSUE TITLE
[WIP] integrate travis and github release

### ISSUE THREAD

**Issue by omochi** [sonsongithub/numsw#47]
メモ

travisのCLIツールを入れる

```
$ gem install travis
```

それを使ってdeploy設定をする

```
$ travis setup releases
```

このコマンドは対話式で、githubのユーザ名、パスワード、2FAトークンを聞かれる。
途中で、API Tokenを暗号化しますか？と聞かれるのでこれをyesにする。

ウィザートが終わると、 `.travis.yml` に `deploy` の項目が追記される。

それを下記のように修正する。

```
language: objective-c
osx_image: xcode8.2
rvm:
- 2.2  
deploy:
  provider: releases
  api_key:
    secure: <生成された文字列のままにする>
  file: Release/numsw-playground.zip
  on:
    tags: true
    repo: sonsongithub/numsw
```
